# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/pipeline/inhouse/DCC/maya/int/modules/rigging/lego/scripts/lego/blocks/legobox/LEGO_00/setting.ui',
# licensing of 'D:/pipeline/inhouse/DCC/maya/int/modules/rigging/lego/scripts/lego/blocks/legobox/LEGO_00/setting.ui' applies.
#
# Created: Mon Mar  8 09:32:05 2021
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(275, 393)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.used_world_cbox = QtWidgets.QCheckBox(self.groupBox)
        self.used_world_cbox.setObjectName("used_world_cbox")
        self.verticalLayout.addWidget(self.used_world_cbox)
        self.mirror_behaviour_cbox = QtWidgets.QCheckBox(self.groupBox)
        self.mirror_behaviour_cbox.setObjectName("mirror_behaviour_cbox")
        self.verticalLayout.addWidget(self.mirror_behaviour_cbox)
        self.align_world_cbox = QtWidgets.QCheckBox(self.groupBox)
        self.align_world_cbox.setObjectName("align_world_cbox")
        self.verticalLayout.addWidget(self.align_world_cbox)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.t_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.t_btn.setObjectName("t_btn")
        self.gridLayout_2.addWidget(self.t_btn, 0, 0, 1, 1)
        self.r_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.r_btn.setObjectName("r_btn")
        self.gridLayout_2.addWidget(self.r_btn, 0, 1, 1, 1)
        self.s_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.s_btn.setObjectName("s_btn")
        self.gridLayout_2.addWidget(self.s_btn, 0, 2, 1, 1)
        self.tx_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.tx_cbox.setChecked(True)
        self.tx_cbox.setObjectName("tx_cbox")
        self.gridLayout_2.addWidget(self.tx_cbox, 1, 0, 1, 1)
        self.rx_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.rx_cbox.setChecked(True)
        self.rx_cbox.setObjectName("rx_cbox")
        self.gridLayout_2.addWidget(self.rx_cbox, 1, 1, 1, 1)
        self.sx_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.sx_cbox.setChecked(True)
        self.sx_cbox.setObjectName("sx_cbox")
        self.gridLayout_2.addWidget(self.sx_cbox, 1, 2, 1, 1)
        self.ty_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.ty_cbox.setChecked(True)
        self.ty_cbox.setObjectName("ty_cbox")
        self.gridLayout_2.addWidget(self.ty_cbox, 2, 0, 1, 1)
        self.ry_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.ry_cbox.setChecked(True)
        self.ry_cbox.setObjectName("ry_cbox")
        self.gridLayout_2.addWidget(self.ry_cbox, 2, 1, 1, 1)
        self.sy_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.sy_cbox.setChecked(True)
        self.sy_cbox.setObjectName("sy_cbox")
        self.gridLayout_2.addWidget(self.sy_cbox, 2, 2, 1, 1)
        self.tz_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.tz_cbox.setChecked(True)
        self.tz_cbox.setObjectName("tz_cbox")
        self.gridLayout_2.addWidget(self.tz_cbox, 3, 0, 1, 1)
        self.rz_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.rz_cbox.setChecked(True)
        self.rz_cbox.setObjectName("rz_cbox")
        self.gridLayout_2.addWidget(self.rz_cbox, 3, 1, 1, 1)
        self.sz_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.sz_cbox.setChecked(True)
        self.sz_cbox.setObjectName("sz_cbox")
        self.gridLayout_2.addWidget(self.sz_cbox, 3, 2, 1, 1)
        self.ro_cbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.ro_cbox.setChecked(True)
        self.ro_cbox.setObjectName("ro_cbox")
        self.gridLayout_2.addWidget(self.ro_cbox, 4, 1, 1, 1)
        self.ro_cbbox = QtWidgets.QComboBox(self.groupBox_2)
        self.ro_cbbox.setObjectName("ro_cbbox")
        self.ro_cbbox.addItem("")
        self.ro_cbbox.addItem("")
        self.ro_cbbox.addItem("")
        self.ro_cbbox.addItem("")
        self.ro_cbbox.addItem("")
        self.ro_cbbox.addItem("")
        self.gridLayout_2.addWidget(self.ro_cbbox, 5, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ik_ref_listview = QtWidgets.QListView(self.groupBox_3)
        self.ik_ref_listview.setObjectName("ik_ref_listview")
        self.horizontalLayout.addWidget(self.ik_ref_listview)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.add_ik_ref_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.add_ik_ref_btn.setObjectName("add_ik_ref_btn")
        self.verticalLayout_3.addWidget(self.add_ik_ref_btn)
        self.remove_ik_ref_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.remove_ik_ref_btn.setObjectName("remove_ik_ref_btn")
        self.verticalLayout_3.addWidget(self.remove_ik_ref_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.used_world_cbox.setText(QtWidgets.QApplication.translate("Form", "Used as World", None, -1))
        self.mirror_behaviour_cbox.setText(QtWidgets.QApplication.translate("Form", "Mirror Behaviour", None, -1))
        self.align_world_cbox.setText(QtWidgets.QApplication.translate("Form", "Align WorldSpace Axis", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "Keyable", None, -1))
        self.t_btn.setText(QtWidgets.QApplication.translate("Form", "T", None, -1))
        self.r_btn.setText(QtWidgets.QApplication.translate("Form", "R", None, -1))
        self.s_btn.setText(QtWidgets.QApplication.translate("Form", "S", None, -1))
        self.tx_cbox.setText(QtWidgets.QApplication.translate("Form", "tx", None, -1))
        self.rx_cbox.setText(QtWidgets.QApplication.translate("Form", "rx", None, -1))
        self.sx_cbox.setText(QtWidgets.QApplication.translate("Form", "sx", None, -1))
        self.ty_cbox.setText(QtWidgets.QApplication.translate("Form", "ty", None, -1))
        self.ry_cbox.setText(QtWidgets.QApplication.translate("Form", "ry", None, -1))
        self.sy_cbox.setText(QtWidgets.QApplication.translate("Form", "sy", None, -1))
        self.tz_cbox.setText(QtWidgets.QApplication.translate("Form", "tz", None, -1))
        self.rz_cbox.setText(QtWidgets.QApplication.translate("Form", "rz", None, -1))
        self.sz_cbox.setText(QtWidgets.QApplication.translate("Form", "sz", None, -1))
        self.ro_cbox.setText(QtWidgets.QApplication.translate("Form", "ro", None, -1))
        self.ro_cbbox.setItemText(0, QtWidgets.QApplication.translate("Form", "XYZ", None, -1))
        self.ro_cbbox.setItemText(1, QtWidgets.QApplication.translate("Form", "YZX", None, -1))
        self.ro_cbbox.setItemText(2, QtWidgets.QApplication.translate("Form", "ZXY", None, -1))
        self.ro_cbbox.setItemText(3, QtWidgets.QApplication.translate("Form", "XZY", None, -1))
        self.ro_cbbox.setItemText(4, QtWidgets.QApplication.translate("Form", "YXZ", None, -1))
        self.ro_cbbox.setItemText(5, QtWidgets.QApplication.translate("Form", "ZYX", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Form", "IK Reference Array", None, -1))
        self.add_ik_ref_btn.setText(QtWidgets.QApplication.translate("Form", "<<", None, -1))
        self.remove_ik_ref_btn.setText(QtWidgets.QApplication.translate("Form", ">>", None, -1))

